# Install with:
#   brew bundle --file Brewfile

tap "getsentry/xcodebuildmcp"
tap "raskrebs/sonar"
tap "steipete/tap"
tap "swiftedmind/cli"

brew "actionlint"
brew "black"
brew "chezmoi"
brew "create-dmg"
brew "difftastic"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "fzf-tab"
brew "getsentry/xcodebuildmcp/xcodebuildmcp"
brew "gh"
brew "git"
brew "git-delta"
brew "go"
brew "isort"
brew "lazygit"
brew "llvm"
brew "mole"
brew "neovim"
brew "node"
brew "node@24"
brew "pipx"
brew "pylint"
brew "python"
brew "raskrebs/sonar/sonar"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "steipete/tap/peekaboo"
brew "stylua"
brew "swiftdraw"
brew "swiftformat"
brew "xcode-build-server"
brew "xcodegen"
brew "zizmor"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "fluidvoice"
cask "font-meslo-lg-nerd-font"
cask "hyperswitcher"
cask "linearmouse"
cask "macshot"
cask "markedit"
cask "pika"
cask "qlmarkdown"
cask "swiftformat-for-xcode"
