model = "gpt-5"
model_reasoning_effort = "high"

[projects."/Users/Shared/Code/app-ios"]
trust_level = "trusted"

[projects."/Users/Shared/Code/charge-sdk-ios"]
trust_level = "trusted"

[mcp_servers.XcodeBuildMCP]
command = "npx"
args = ["-y", "xcodebuildmcp@latest"]
env = { "XCODEBUILDMCP_ENABLED_WORKFLOWS" = "device,simulator,swift-package,logging,doctor,project-discovery" }

[mcp_servers.sosumi]
command = "npx"
args = ["-y", "mcp-remote", "https://sosumi.ai/mcp"]

[mcp_servers.spm-scout]
command = "/Users/Shared/Code/SwiftPackageScout/.build/arm64-apple-macosx/debug/spm-scout-mcp"
args = []

