# git:
#   tabWidth: 2
#   pagers:
#     - colorArg: always
#       pager: "delta --navigate --syntax-theme=ansi --dark --line-numbers --paging=never --tabs=2"
# os:
#   edit: "nvim {{filename}}"
#   open: "open {{filename}}"
# notARepository: skip

git:
  disableForcePushing: true
  tabWidth: 2
  diffRenderers:
    - command: delta --dark --paging=never --line-numbers --side-by-side
    - command: difft --color=always --syntax-highlight=on --tab-width=2
      type: extDiff
    - type: rawGit # plain diff fallback
os:
  edit: "nvim {{filename}}"
  open: "open {{filename}}"
gui:
  commandLogSize: 2
  mainPanelSplitMode: vertical
  sidePanelWidth: 0.2
  theme:
    selectedLineBgColor:
      - reverse
    inactiveViewSelectedLineBgColor:
      - default
